### ISSUE TITLE
unable to install unf_ext from gem

### ISSUE THREAD

**Issue by michalejoye** [knu/ruby-unf_ext#43]
I get this error when i try to install this from gem
[gem_make.log](https://github.com/knu/ruby-unf_ext/files/2011139/gem_make.log)

**Comment by Cyberbeni** [comment]
It worked for me on macOS 10.14 with xcode 10 but didn't work on 10.13.6 with xcode 10, only with xcode 9.3
Xcode -> Preferences -> Locations -> Command Line Tools

**Comment by ReDetection** [comment]
happens for me on macOS 10.14 with xcode 10. in the `mkmf.log` it's written 
```
In file included from conftest.c:1:
In file included from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h:33:
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^~~~~~~~~~~~~~~
```
how to investigate that?
