### ISSUE TITLE
Failing to compile on macOS/Ruby 2.7.1 but not sure why

### ISSUE THREAD

**Issue by csuhta** [knu/ruby-unf_ext#57]
This is what I have in my logs for installing unf_ext. I'm not sure why this isn't working, it seems to be pointing to a source-code issue only, not failing to find other files, etc

If I can provide any other information, please let me know.

```
Installing unf_ext 0.0.7.7 (was 0.0.7.6) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/Csuhta/.gem/ruby/2.7.1/gems/unf_ext-0.0.7.7/ext/unf_ext
/Users/Csuhta/.rubies/ruby-2.7.1/bin/ruby -I /Users/Csuhta/.rubies/ruby-2.7.1/lib/ruby/2.7.0 -r ./siteconf20200401-85002-qhwila.rb extconf.rb
checking for -lstdc++... yes
creating Makefile

current directory: /Users/Csuhta/.gem/ruby/2.7.1/gems/unf_ext-0.0.7.7/ext/unf_ext
make "DESTDIR=" clean

current directory: /Users/Csuhta/.gem/ruby/2.7.1/gems/unf_ext-0.0.7.7/ext/unf_ext
make "DESTDIR="
compiling unf.cc
In file included from unf.cc:3:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby.h:33:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/ruby.h:29:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/defines.h:171:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/missing.h:25:
/usr/local/include/jemalloc/jemalloc.h:226:28: error: exception specification in declaration does not match previous declaration
    void JEMALLOC_NOTHROW       *je_malloc(size_t size)
                                 ^
/usr/local/include/jemalloc/jemalloc.h:69:21: note: expanded from macro 'je_malloc'
#  define je_malloc malloc
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/malloc/_malloc.h:40:7: note: previous declaration is here
void    *malloc(size_t __size) __result_use_check __alloc_size(1);
         ^
In file included from unf.cc:3:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby.h:33:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/ruby.h:29:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/defines.h:171:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/missing.h:25:
/usr/local/include/jemalloc/jemalloc.h:229:28: error: exception specification in declaration does not match previous declaration
    void JEMALLOC_NOTHROW       *je_calloc(size_t num, size_t size)
                                 ^
/usr/local/include/jemalloc/jemalloc.h:63:21: note: expanded from macro 'je_calloc'
#  define je_calloc calloc
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/malloc/_malloc.h:41:7: note: previous declaration is here
void    *calloc(size_t __count, size_t __size) __result_use_check __alloc_size(1,2);
         ^
In file included from unf.cc:3:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby.h:33:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/ruby.h:29:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/defines.h:171:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/missing.h:25:
/usr/local/include/jemalloc/jemalloc.h:231:38: error: exception specification in declaration does not match previous declaration
JEMALLOC_EXPORT int JEMALLOC_NOTHROW    je_posix_memalign(void **memptr,
                                        ^
/usr/local/include/jemalloc/jemalloc.h:77:29: note: expanded from macro 'je_posix_memalign'
#  define je_posix_memalign posix_memalign
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/malloc/_malloc.h:52:7: note: previous declaration is here
int      posix_memalign(void **__memptr, size_t __alignment, size_t __size) __OSX_AVAILABLE_STARTING(__MAC_10_6, __IPHONE_3_0);
         ^
In file included from unf.cc:3:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby.h:33:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/ruby.h:29:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/defines.h:171:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/missing.h:25:
/usr/local/include/jemalloc/jemalloc.h:238:28: error: exception specification in declaration does not match previous declaration
    void JEMALLOC_NOTHROW       *je_realloc(void *ptr, size_t size)
                                 ^
/usr/local/include/jemalloc/jemalloc.h:79:22: note: expanded from macro 'je_realloc'
#  define je_realloc realloc
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/malloc/_malloc.h:43:7: note: previous declaration is here
void    *realloc(void *__ptr, size_t __size) __result_use_check __alloc_size(2);
         ^
In file included from unf.cc:3:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby.h:33:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/ruby.h:29:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/defines.h:171:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/missing.h:25:
/usr/local/include/jemalloc/jemalloc.h:240:39: error: exception specification in declaration does not match previous declaration
JEMALLOC_EXPORT void JEMALLOC_NOTHROW   je_free(void *ptr)
                                        ^
/usr/local/include/jemalloc/jemalloc.h:65:19: note: expanded from macro 'je_free'
#  define je_free free
                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/malloc/_malloc.h:42:7: note: previous declaration is here
void     free(void *);
         ^
In file included from unf.cc:3:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby.h:33:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/ruby.h:29:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/defines.h:171:
In file included from /Users/Csuhta/.rubies/ruby-2.7.1/include/ruby-2.7.0/ruby/missing.h:25:
/usr/local/include/jemalloc/jemalloc.h:279:28: error: exception specification in declaration does not match previous declaration
    void JEMALLOC_NOTHROW       *je_valloc(size_t size) JEMALLOC_CXX_THROW
                                 ^
/usr/local/include/jemalloc/jemalloc.h:83:21: note: expanded from macro 'je_valloc'
#  define je_valloc valloc
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:735:7: note: previous declaration is here
void    *valloc(size_t);                        
         ^
6 errors generated.
make: *** [unf.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/Csuhta/.gem/ruby/2.7.1/gems/unf_ext-0.0.7.7 for inspection.
Results logged to /Users/Csuhta/.gem/ruby/2.7.1/extensions/x86_64-darwin-19/2.7.0-static/unf_ext-0.0.7.7/gem_make.out

An error occurred while installing unf_ext (0.0.7.7), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.7' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  discordrb was resolved to 3.3.0, which depends on
    discordrb-webhooks was resolved to 3.3.0, which depends on
      rest-client was resolved to 2.1.0, which depends on
        http-cookie was resolved to 1.0.3, which depends on
          domain_name was resolved to 0.5.20190701, which depends on
            unf was resolved to 0.1.4, which depends on
              unf_ext
```

**Comment by jakubgs** [comment]
Seeing the same issue. No clue what this is about.

**Comment by csuhta** [comment]
I was able to fix this on MacOS 10.15.4, but I'm not sure what did it:

- Reinstall MacOS Developer Tools
- Re-install Jemalloc and Ruby (using homebrew and ruby-install)
- Gem bundled correctly after that

**Comment by edbond** [comment]
After reinstalling jemalloc gem installed:

```sh
▶ brew reinstall jemalloc
==> Reinstalling jemalloc
==> Downloading https://homebrew.bintray.com/bottles/jemalloc-5.2.1_1.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/b1/b1b211e5bead798c236d478dd74310a97a7b59470f607b608c07222648b08bf5?__gda__=exp=1587473617~hmac=2fe57
######################################################################## 100.0%
==> Pouring jemalloc-5.2.1_1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/jemalloc/5.2.1_1: 16 files, 2MB

▶ gem install unf_ext -v '0.0.7.6'
Building native extensions. This could take a while...
Successfully installed unf_ext-0.0.7.6
Parsing documentation for unf_ext-0.0.7.6
Installing ri documentation for unf_ext-0.0.7.6
Done installing documentation for unf_ext after 1 seconds
1 gem installed
```

**Comment by fkapsahili** [comment]
If anyone should have a similar problem:
I still got the same error despite these steps. It just didn't work when the Command Tools were installed - the following steps, one after the other, were a workaround for me:

```
sudo rm -rf /Library/Developer/CommandLineTools
gem install unf_ext -v 0.0.7.7
sudo xcode-select --install
```

**Comment by marianodominguez** [comment]
Is there a solution for Linux? I installed all development tools and c++ devel libs, build is failing with 2.7
Centos 7

[error.txt](https://github.com/knu/ruby-unf_ext/files/6593242/error.txt)

**Comment by bcouetil** [comment]
If you come here in 2023, DON'T UNINSTALL anything related to XCode. No need.

There are great chance it is because your system Ruby, which is old, is loaded before your Homebrew Ruby.

Just follow [this guide](https://mac.install.guide/ruby/13.html) to have a `ruby` command using your latest Ruby installation.
