### ISSUE TITLE
Error compiling on Ruby 1.8.7

### ISSUE THREAD

**Issue by postmodern** [knu/ruby-unf_ext#5]
<pre>
g++ -I. -I. -I/opt/rubies/ruby-1.8.7-p371/lib/ruby/1.8/x86_64-linux -I. -DHAVE_RUBY_ENCODING_H    -fPIC -g -O2    -c unf.cc
In file included from unf.cc:5:0:
/usr/include/ruby/encoding.h:101:68: error: expected identifier before numeric constant
/usr/include/ruby/encoding.h:101:68: error: expected ‘,’ or ‘...’ before numeric constant
/usr/include/ruby/encoding.h:101:73: error: expected constructor, destructor, or type conversion before ‘;’ token
In file included from unf.cc:5:0:
/usr/include/ruby/encoding.h:213:65: error: declaration of C function ‘long int rb_memsearch(const void*, long int, const void*, long int, rb_encoding*)’ conflicts with
In file included from /opt/rubies/ruby-1.8.7-p371/lib/ruby/1.8/x86_64-linux/ruby.h:756:0,
                 from unf.cc:3:
/opt/rubies/ruby-1.8.7-p371/lib/ruby/1.8/x86_64-linux/intern.h:387:6: error: previous declaration ‘long int rb_memsearch(const void*, long int, const void*, long int)’ here
make: *** [unf.o] Error 1
</pre>

It does successfully build on Ruby 1.9.3. I would be OK if unf_ext set `gemspec.required_ruby_version` to `>= 1.9.1`.
