### ISSUE TITLE
0.0.7.2 fails to build on arm with gcc 6.3.0

### ISSUE THREAD

**Issue by LuisDominguez** [knu/ruby-unf_ext#34]
i try installing in raspberry pi 
and get:

`An error occurred while installing unf_ext (0.0.7.2), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.2'` succeeds before bundling.`

`unf/table.hh:13539:25: error: narrowing conversion of ‘-113’ from ‘int’ to ‘char’ inside { } [Wnarrowing]
unf/table.hh:13539:25: error: narrowing conversion of ‘-81’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
unf/table.hh:13539:25: error: narrowing conversion of ‘-27’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
unf/table.hh:13539:25: error: narrowing conversion of ‘-66’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
unf/table.hh:13539:25: error: narrowing conversion of ‘-105’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
unf/table.hh:13539:25: error: narrowing conversion of ‘-27’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
unf/table.hh:13539:25: error: narrowing conversion of ‘-106’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]`

Ruby version: ruby 2.1.5p273 (2014-11-13 revision 48405) [armv7l-linux-eabihf]
Bundler version: Bundler version 1.16.0 (2017-10-31 commit 10f20fa33)

**Comment by LuisDominguez** [comment]
Solved! 
run` bundle update unf_ext `
