### PR TITLE
Fix use of designated initializers.

### LINKED ISSUE #74: Compilation Error with non-trivial designated initializers when installing unf_ext (0.0.9) on Ruby 2.3.1 on Linux
### Issue Summary
I am encountering an issue while trying to install the `unf_ext` gem. The installation fails with a compilation error, and I believe it might be related to non-trivial designated initializers.

### Environment
- **Ruby version:** 2.3.1
- **Operating system:** Linux
- **Installation command:** `gem install unf_ext -v 0.0.9`

### Error Message
```
Building native extensions. This could take a while...
ERROR: Error installing unf_ext:
ERROR: Failed to build gem native extension.

current directory: /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.9/ext/unf_ext
/opt/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20231113-4568-rh260p.rb extconf.rb
checking for main() in -lstdc++... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/unf_ext-0.0.9/mkmf.log

current directory: /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.9/ext/unf_ext
make "DESTDIR=" clean

current directory: /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.9/ext/unf_ext
make "DESTDIR="
compiling unf.cc
cc1plus: warning: command line option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wimplicit-function-declaration’ is valid for C/ObjC but not for C++ [enabled by default]
unf.cc:39:3: sorry, unimplemented: non-trivial designated initializers not supported
   };
   ^
unf.cc:39:3: sorry, unimplemented: non-trivial designated initializers not supported
make: *** [unf.o] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.9 for inspection.
Results logged to /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/unf_ext-0.0.9/gem_make.out
```

### Additional Information
I have checked the mkmf.log file, and it seems to be pointing to an issue with non-trivial designated initializers. I am using Ruby 2.3.1 on a Linux system, and the installation command used is as mentioned above.

### PR DESCRIPTION
**Pull request by igorpeshansky**
Make them compatible with earlier versions of GCC.

Fixes #74.

### CODE REVIEW

**Review by lemsx1 — APPROVED** [review]

**Comment by lemsx1** [comment]
I can confirm this fixes the issue for me:


```
 /opt/ruby/3.1.4/lib64/ruby/gems/3.1.0/gems/unf_ext-0.0.9/ext/unf_ext # build-env-baapi.sh make
Using path '/opt/rh/devtoolset-7/root/usr/bin:/opt/ruby/3.1.4/bin:/opt/rh/devtoolset-7/root/usr/bin:/usr/bin:/bin:/usr/local/bin:/opt/ruby/3.1.4/bin:/bin:/usr/bin:/bb/bin:/opt/dell/srvadmin/bin:/opt/dell/srvadmin/sbin:/sbin:/usr/sbin:/usr/local/sbin:/bb/admin:/bb/admin/qc:/opt/utils/admin:/root/bin'
compiling unf.cc
linking shared-object unf_ext.so
/opt/ruby/3.1.4/lib64/ruby/gems/3.1.0/gems/unf_ext-0.0.9/ext/unf_ext # echo $?
0
```


# lsb_release -r
Release:	7.9

using devtoolset-7

**Comment by huarmenta** [comment]
Hey @lemsx1 Can you please share with us what exactly should we do?

**Comment by lemsx1** [comment]
For this you can simply go to
the unpacked directory where `gem` failed to compile and copy/paste the patch (line 33 of the file) and hit: make && make install. 
Ideally, you can clone the repo, apply this patch to your local copy, and do a new gem (rake build) to install that copy instead.

**Comment by huarmenta** [comment]
@lemsx1 Thanks! will try!

**Comment by loudgazelle** [comment]
@knu Will you please review this patch? It resolves #74 which was introduced by #72

**Review by AsefJafarli — APPROVED** [review]
passed

**Comment by ABHIJITH-EA** [comment]
I have tested the patch and wanted to bring to your attention a potential compatibility concern with Ruby versions lower than 2.7.0, despite the gemspec specifying a requirement of ">= 2.2". The error encountered during compilation in Ruby version 2.3.1 is as follows:
```
compiling unf.cc
cc1plus: warning: command line option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wimplicit-function-declaration’ is valid for C/ObjC but not for C++ [enabled by default]
unf.cc:45:3: error: ‘rb_data_type_struct::<anonymous struct>’ has no non-static data member named ‘dcompact’
   };
   ^
make: *** [unf.o] Error 1
```
The "dcompact" member, which I believe was introduced in Ruby version 2.7.0, is the source of this issue. This patch appears to not fully resolve the issue introduced by  #72

**Comment by knu** [comment]
Hmm, and the irony here is that despite the extension being updated to support the C API of Ruby 2.7+, the main functionality this library provides is in Ruby 2.6+ as String#unicode_normalize. 🥺

**Comment by knu** [comment]
I've just released a new version of the domain_name gem that requires Ruby >=2.7 and no longer depends on unf and unf_ext.  I think that will remove one of the biggest reasons people would ever need to get unf_ext installed.

**Comment by Bo98** [comment]
> I think that will remove one of the biggest reasons people would ever need to get unf_ext installed.

Did the 0.2.0 betas on `unf` work out where the native parts were conditionally used based on the Ruby version?

**Comment by ABHIJITH-EA** [comment]
@igorpeshansky Thanks for the fix! I tested it.I can confirm it's all good now.
```
compiling unf.cc
cc1plus: warning: command line option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wimplicit-function-declaration’ is valid for C/ObjC but not for C++ [enabled by default]
linking shared-object unf_ext.so
```

**Review by knu — APPROVED** [review]

**Comment by igorpeshansky** [comment]
Thanks, @knu. Is this ready to merge now, or would you need me to squash the commits?

**Comment by knu** [comment]
No problem.  I'll squash merge this.
